-- Crear tablas nuevamente
CREATE TABLE IF NOT EXISTS clients (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name  VARCHAR(120) NOT NULL,
                                       last_name  VARCHAR(120),
                                       phone VARCHAR(40),
                                       email VARCHAR(120),
                                       dni VARCHAR(120)
);

CREATE TABLE IF NOT EXISTS pets (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    client_id INT NOT NULL,
                                    name   VARCHAR(120) NOT NULL,
                                    species VARCHAR(60),
                                    breed   VARCHAR(60),
                                    birthdate   DATE,
                                    CONSTRAINT fk_pets_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointments (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            pet_id INT NOT NULL,
                                            date_time TIMESTAMP NOT NULL,
                                            reason VARCHAR(200),
                                            notes  VARCHAR(500),
                                            status VARCHAR(20),
                                            CONSTRAINT fk_appts_pet FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pets_client ON pets(client_id);
CREATE INDEX IF NOT EXISTS idx_appts_pet  ON appointments(pet_id);
CREATE INDEX IF NOT EXISTS idx_appts_dt   ON appointments(date_time);